### ISSUE TITLE
rw_top_trumps: Out of bounds for instance reported for valid arguments

### ISSUE THREAD

**Issue by dietmarwo** [ttusar/coco-gbea#2]
See a lot of messages like
```
Out of bounds for instance 4, i = 50, x[50] = 37.000000, min[2] = 21.000000, max[2] = 36.000000
```
reported for valid arguments. To reproduce do
```
pip install fcmaes
```
and configure the following search:

```python
from fcmaes.optimizer import De_cpp
from scipy.optimize import Bounds

def de_search(fun, lbounds, ubounds, budget):       
    x_min, y, nfev = De_cpp(budget).minimize(fun), Bounds(lbounds, ubounds))
    return x_min
```

To make sure only valid arguments are used we can extend the search:

```python
class wrapper(object):
   
    def __init__(self, fun, lbounds, ubounds):
        self.fun = fun  
        self.lbounds = lbounds
        self.ubounds = ubounds

    def __call__(self, x):
        return self.fun(np.maximum(np.minimum(x, self.ubounds), self.lbounds))

def de_search2(fun, lbounds, ubounds, budget):       
    x_min, y, nfev = De_cpp(budget).minimize(wrapper(fun, lbounds, ubounds),
            Bounds(lbounds, ubounds))
    return np.maximum(np.minimum(x_min, ubounds), lbounds)
```
We still see "Out of bounds" messages generated by rw_top_trumps.cpp here:

```c++
  // Check if out of bounds
  for (size_t i = 0; i < m; i++) {
    min_vector[i] = min[i];
    max_vector[i] = max[i];
    for (size_t j = 0; j < n; j++) {
      x_vector[j * m + i] = x[j * m + i];
      if (x_vector[j * m + i] < min_vector[i] || x_vector[j * m + i] > max_vector[i]) {
        fprintf(stderr, "Out of bounds for instance %lu, ", instance);
        fprintf(stderr, "i = %lu, ", j * m + i);
        fprintf(stderr, "x[%lu] = %f, min[%lu] = %f, max[%lu] = %f\n",
            j * m + i, x_vector[j * m + i], i, min_vector[i], i, max_vector[i]);
        outOfBounds = true;
        break;
      }
    }
  }
```

**Comment by ttusar** [comment]
~~Just to make sure - does this mean the previous issue is not a problem any longer?~~

Never mind, this one is about the experiments, the other is about postprocessing...

**Comment by dietmarwo** [comment]
Yes, both issues are completely unrelated

**Comment by ttusar** [comment]
Can you also provide the code snippet which uses `de_search2`?

**Comment by dietmarwo** [comment]
in  coco-gbea/code-experiments/build/python/rw_example_experiment.py
we have:
```python
from cocoex.solvers import random_search, de_search, de_search2
...
    # Set solver (COCO's random search only evaluates feasible solutions)
    solver = de_search2 # random_search
```
no other changes. I added the de_search2 code to /home/xxx/git/coco-gbea/code-experiments/build/python/python/solvers.py

Another solver I tried:

```python
from fcmaes.optimizer import Bite_cpp

def bite_search(fun, lbounds, ubounds, budget):       
    x_min, y, nfev = Bite_cpp(budget).minimize(fun, Bounds(lbounds, ubounds))
    return x_min
```

Doesn't have the issue, same with random_search. So I suspect it is related to the fact that De_cpp sometimes creates
samples with some variables at - but not out of - the limits.

**Comment by ttusar** [comment]
I have issues with this code

```
FileNotFoundError: Could not find module 'C:\Anaconda3\envs\py38gbea\lib\site-packages\fcmaes\lib\libacmalib.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

What do I need to do to make it work?

**Comment by ttusar** [comment]
> Doesn't have the issue, same with random_search. So I suspect it is related to the fact that De_cpp sometimes creates
> samples with some variables at - but not out of - the limits.

Well, judging from the error message (value is 37.0, but should be at most 36.0), it doesn't seem to be on the limits... Might be a rounding issue... It's really hard to say without being able to reproduce the error.

```
Out of bounds for instance 4, i = 50, x[50] = 37.000000, min[2] = 21.000000, max[2] = 36.000000
```

**Comment by dietmarwo** [comment]
Was also supecting a rounding issue. So you are running on Windows. Will try to reproduce your "Could not find module" error. 
May be related to the use of environments. 'pip install fcmaes' installs the code to the anaconda main site-packages folder. Somehow the lib folder seems missing in the py38gbea environment. So you executed  'pip install fcmaes' while being in the py38gbea virtual environment?

**Comment by ttusar** [comment]
Yes, of course. This is the entire error message:
````
Traceback (most recent call last):
  File "D:/Delo/Github/ttusar-coco-gbea/code-experiments/build/python/rw_example_experiment.py", line 35, in <module>
    from fcmaes.optimizer import De_cpp
  File "C:\Anaconda3\envs\py38gbea\lib\site-packages\fcmaes\optimizer.py", line 14, in <module>
    from fcmaes import cmaes, de, cmaescpp, decpp, dacpp, hhcpp, gcldecpp, lcldecpp, ldecpp, csmacpp, bitecpp
  File "C:\Anaconda3\envs\py38gbea\lib\site-packages\fcmaes\cmaescpp.py", line 185, in <module>
    libcmalib = ct.cdll.LoadLibrary(basepath + '/lib/libacmalib.dll')  
  File "C:\Anaconda3\envs\py38gbea\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\envs\py38gbea\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Anaconda3\envs\py38gbea\lib\site-packages\fcmaes\lib\libacmalib.dll' (or one of its dependencies). Try using the full path with constructor syntax.
````

**Comment by ttusar** [comment]
Hm... this is strange. I do have the mentioned library in the exact path it is complaining about...

**Comment by dietmarwo** [comment]
On linux I tried

python3 -m venv py38gbea
source env/bin/activate
pip install fcmaes

Then I see the dll in 

~/py38gbea/lib/python3.8/site-packages/fcmaes/lib/

Will retry with Windows.

**Comment by ttusar** [comment]
I have two libraries in `C:\Anaconda3\envs\py38gbea\Lib\site-packages\fcmaes\lib\`:
- `libacmalib.dll`
- `libgtoplib.dll`

Should there be any others (the error message mentions dependencies)?

**Comment by dietmarwo** [comment]
Ok, these dlls are build using mingw. They require VC redist dlls be installed. 
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
Its mentioned at https://github.com/dietmarwo/fast-cma-es/ . Its a windows related issue. 
But wait a minute, I can create a solver using the native Python version of this DE variant.

**Comment by ttusar** [comment]
I installed it (and restarted the computer), but the error is exactly the same...

**Comment by dietmarwo** [comment]
You may try

from fcmaes.optimizer import Bite_cpp, De_cpp, De_python
```python
def de_search3(fun, lbounds, ubounds, budget):       
    x_min, y, nfev = De_python(budget, popsize=31).minimize(wrapper(fun, lbounds, ubounds),
            Bounds(lbounds, ubounds))
    return np.maximum(np.minimum(x_min, ubounds), lbounds)
```    
which doesn't require the dll. 
   
I checked on my windows machine, it works there. Not sure what can be missing. Will investigate further.

**Comment by dietmarwo** [comment]
Tried https://github.com/lucasg/Dependencies to check the dependencies of the dll. Found
C:\Users\xxx\anaconda3\Library\mingw-w64\bin\libgcc_s_seh-1.dll
C:\Users\xxx\anaconda3\Library\mingw-w64\bin\libstdc++-6.dll
But you also have anaconda installed. May be the path is not in your environment setting?
I can reproduce the issue after renaming one of these files and additionaly renaming my mingw installation folder. Will try to include them in the next fcmaes update.

Finally I got the dll dependency issue fixed by including these two dlls in fcmaes. I will prepare a new fcmaes release today, until then you may use  de_search3 which is pure Python code not using any dlls. The Python DE implementation is slower but equivalent and also reproduces the issue.

**Comment by ttusar** [comment]
The library issue appears when importing `fcmaes.optimizer`, so the new `de_search3` doesn't really make any difference...

**Comment by ttusar** [comment]
In any case, I'm not sure the exception you are getting has anything to do with coco-gbea, but is rather an issue of the algorithm, which for some reason proposes to use value 37 when only values up to 36 are allowed. I think this should be looked into...

**Comment by dietmarwo** [comment]
Released fcmaes 1.2.20 ( pip install fcmaes --upgrade ) and the dll issue should be gone. 
Regarding the algorithm: 
if we use
np.maximum(np.minimum(x_min, ubounds), lbounds)
to force that we stay inside the defined limits, and the rounding is done inside gbea, what do you suggest should be changed 
at the algorithm level? How should the algorithm know about a wrong rounding inside the gbea fitness function?

**Comment by ttusar** [comment]
> Released fcmaes 1.2.20 ( pip install fcmaes --upgrade ) and the dll issue should be gone.

It is still not gone, because the library is loaded in `cmaescpp.py`, which is invoked in line
```
from fcmaes import cmaes, de, cmaescpp, decpp, dacpp, hhcpp, gcldecpp, lcldecpp, ldecpp, csmacpp, bitecpp
```
in `fcmaes.optimzer.py`

**Comment by dietmarwo** [comment]
found a trivial algorithm which reproduces the issue
```python
def lb_search(fun, lbounds, ubounds, budget):     
    y1 = fun(lbounds)
    y1 = fun(ubounds)
    return lbounds
```
How does this algorithm violate any constraints?

**Comment by dietmarwo** [comment]
cmaescpp.py does now in the new version:

else:
    os.environ['PATH'] = (basepath + '/lib') + os.pathsep + os.environ['PATH']
    libcmalib = ct.cdll.LoadLibrary(basepath + '/lib/libacmalib.dll')  

and since the missing libraries are now in anaconda3/lib/python3.8/site-packages/fcmaes/lib/
this should work - at least on my windows machine it works for version 1.2.20

**Comment by ttusar** [comment]
Ok, I can recreate the issue now with `lb_search`. I don't understand how this never came up before...

**Comment by dietmarwo** [comment]
>It is still not gone, because the library is loaded in cmaescpp.py, which is invoked in line

Also can recreate this issue now. One more indirect dependency missing. Will create version 1.2.21

**Comment by ttusar** [comment]
Found and fixed the issue, thanks for the help.

It happened because we extend the lower and upper bounds to make it easier for continuous algorithms to interface the problem. And that extension was not accounting for rounding errors (another example had this fixed, but we somehow missed it here). Please, let me know if it works for you now.

**Comment by dietmarwo** [comment]
Will check.

for fcmaes finally libwinpthread-1.dll was missing, fcmaes 1.2.21 is released. 
pip install fcmaes --upgrade should finally fix the issue. 

It is difficult to detect these issues because most have installed anaconda which has the dlls (may by you decided not
add it to the PATH environment variable) or have installed mingw64. In both cases the error doesn't occur. 

By the way, the reason I wanted to check these two algorithms (BiteOpt and fcmaes-DE) is because
both were successfully applied at the 11th China trajectory optimization competition (CTOC)
for a another simulation based problem: The simulation of two satellites covering a number of
targets on earth. Both algorithms are quite new - Biteopt improved a lot this year. They are designed to work in "parallel retry" scenarios. The parallelization capabilities of modern processors are used to execute a lot of optimization runs in parallel. 
They are tuned not for the average but for the best result out of a number of runs. For CTOC about 2000 optimization runs were executed on a number of machines (about 128 runs in parallel) for each propagation of the state of the two satellites.

**Comment by dietmarwo** [comment]
Can confirm the issue is fixed. Thanks for you help fixing the fcmaes dll issue.

**Comment by ttusar** [comment]
Glad to hear it.
